controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

app_catch_all:
  path: /{path}
  controller: App\Controller\WelcomeController::index
  requirements:
    path: .*